### PR TITLE
Quiz

### PR DESCRIPTION
**Pull request by duggerNot**
Foundation quiz submission

### CODE REVIEW

**Comment by dtinsley333** [comment]
It looks good but I would do a few refactors to make your code a little cleaner. booleans are false by default so you don't have to set them to default. You can reduce "if" statements and complexity if you do something like this: 
```
        public bool ItemIsOnMenu(string item)
        {
            return MenuItems.Exists(x => x.Name == item);
            //{
            //    return true;
            //}
            //else
            //{
            //    return false;
            //}
        }
```

**Comment by dtinsley333** [comment]
Here is another example where the code could use a little simplyfing. I left the original code for comparison. 
```
 public bool VerifyOrderComplete()
        {
            //if (Drink == null)
            //{
            //    return false;
            //}
            //else if (Entree == null)
            //{
            //    return false;
            //}
            //else if (Dessert == null)
            //{
            //    return false;
            //}
            //else
            //{
            //    return true;
            //}
            var orderIsComplete = ((Drink != null) && (Entree != null) && (Dessert != null));
            return orderIsComplete;
        }

```

**Comment by dtinsley333** [comment]
Here is another example that could be simplified. I also think you are supposed to verify that the items in the order are actually on the menu for the restaurant. 
```
 public bool ReadyToPlaceOrder(Order order, Restaurant foodPlace)
        {            
            //if (order.VerifyOrderComplete())
            //{
            //        if (foodPlace.MenuItems.Count == 3)
            //        {
            //            return true;
            //        }
            //        else
            //        {
            //            return false;
            //        }
            //}
            //else
            //{
            //    return false;
            //}
            var isReadyToPlaceOrder=(order.VerifyOrderComplete())&& (foodPlace.MenuItems.Count == 3);
            return isReadyToPlaceOrder;
        }
```

**Comment by dtinsley333** [comment]
This function needs to simplified as well. 
```

        public bool ItemIsOnMenu(MenuItem item)
        {
            //if (MenuItems.Contains(item))
            //{
            //    return true;
            //}
            //else
            //{
            //    return false;
            //}
            return MenuItems.Contains(item);
        }
```

**Comment by chortlehoort** [comment]
@duggerNot merge it!  👍

**Pull request merged**
